In [12]:
from ucimlrepo import fetch_ucirepo 
import numpy as np

In [ ]:

# fetch dataset 
ai4i_2020_predictive_maintenance_dataset = fetch_ucirepo(id=601) 
  
# data (as pandas dataframes) 
X = ai4i_2020_predictive_maintenance_dataset.data.features 
y = ai4i_2020_predictive_maintenance_dataset.data.targets 
  
# metadata 
print(ai4i_2020_predictive_maintenance_dataset.metadata) 
  
# variable information 
print(ai4i_2020_predictive_maintenance_dataset.variables)

In [ ]:
# dict_keys(['ids', 'features', 'targets', 'original', 'headers'])

In [21]:
ai4i_2020_predictive_maintenance_dataset.data['ids']

        UID Product ID
0         1     M14860
1         2     L47181
2         3     L47182
3         4     L47183
4         5     L47184
...     ...        ...
9995   9996     M24855
9996   9997     H39410
9997   9998     M24857
9998   9999     H39412
9999  10000     M24859

[10000 rows x 2 columns]

In [6]:
X

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
0,M,298.1,308.6,1551,42.8,0
1,L,298.2,308.7,1408,46.3,3
2,L,298.1,308.5,1498,49.4,5
3,L,298.2,308.6,1433,39.5,7
4,L,298.2,308.7,1408,40.0,9
...,...,...,...,...,...,...
9995,M,298.8,308.4,1604,29.5,14
9996,H,298.9,308.4,1632,31.8,17
9997,M,299.0,308.6,1645,33.4,22
9998,H,299.0,308.7,1408,48.5,25
9999,M,299.0,308.7,1500,40.2,30

In [16]:
y.groupby(['Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']).value_counts()

Machine failure  TWF  HDF  PWF  OSF  RNF
0                0    0    0    0    0      9643
                                     1        18
1                0    0    0    0    0         9
                                1    0        78
                           1    0    0        80
                                1    0        11
                      1    0    0    0       106
                                1    0         6
                           1    0    0         3
                 1    0    0    0    0        42
                                     1         1
                                1    0         2
                           1    1    0         1
Name: count, dtype: int64